-- Generated by content-api/seed-from-data-js.mjs — do not hand-edit.

-- events -> events (5)
INSERT OR REPLACE INTO events (id,title,date,time,location,description,register_url,status,demo,position,created_at,updated_at) VALUES ('ev1','כנס המורים הארצי תשפ"ז','2026-11-15','09:00–17:00','הרדוף','הכנס השנתי לכל המחנכים העוסקים בעבודה פעילה בגנים ובבתי ספר ולדורף.','https://forms.google.com/','published',1,0,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO events (id,title,date,time,location,description,register_url,status,demo,position,created_at,updated_at) VALUES ('ev2','כנס גננות ולדורף','2026-11-22','08:30–15:00','קריית טבעון','יום עיון ארצי לגננות: התפתחות הילד בגיל הרך, שירים ומעגלי בוקר.','https://forms.google.com/','published',1,1,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO events (id,title,date,time,location,description,register_url,status,demo,position,created_at,updated_at) VALUES ('ev3','סדנת הכשרת מורים — מתמטיקה','2026-12-05','10:00–16:00','ירושלים','סדנה מעשית להוראת חשבון בכיתות א׳–ד׳ ברוח ולדורף.',NULL,'draft',1,2,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO events (id,title,date,time,location,description,register_url,status,demo,position,created_at,updated_at) VALUES ('ev4','יום עיון להורים','2027-01-18','09:00–13:00','תל אביב','מפגש פתוח להורים: מהו חינוך ולדורף וכיצד בוחרים מסגרת לילד.','https://forms.google.com/','published',1,3,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO events (id,title,date,time,location,description,register_url,status,demo,position,created_at,updated_at) VALUES ('ev5','פתיחת שנת הלימודים תשפ"ז','2026-09-01',NULL,NULL,'ברכת הפורום הארצי לפתיחת שנת הלימודים בכל מוסדות ולדורף.',NULL,'published',1,4,strftime('%s','now'),strftime('%s','now'));

-- news -> news (6)
INSERT OR REPLACE INTO news (id,title,date,section,summary,link,status,demo,position,created_at,updated_at) VALUES ('nw1','איך נולדת תקופה?','2026-07-22','מאמרים','הצצה אל מאחורי הקלעים של עבודת מחנך ולדורף בבניית תקופת לימוד.',NULL,'approved',0,0,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO news (id,title,date,section,summary,link,status,demo,position,created_at,updated_at) VALUES ('nw2','אסופת קישורים בנושא החופש הגדול','2026-07-20','מודעות ופרסומים','כלים ורעיונות למשפחות לקראת חופשת הקיץ.',NULL,'approved',0,1,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO news (id,title,date,section,summary,link,status,demo,position,created_at,updated_at) VALUES ('nw3','שלום כיתה א''','2026-07-20','מודעות ופרסומים','מדריך מקיף להורים לקראת המעבר לבית הספר.',NULL,'approved',0,2,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO news (id,title,date,section,summary,link,status,demo,position,created_at,updated_at) VALUES ('nw4','"זה היה בחברות"','2026-06-27','מאמרים','מדריך למחנך להתמודדות עם אלימות ומשחקי נערים בגיל המצווה.',NULL,'approved',0,3,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO news (id,title,date,section,summary,link,status,demo,position,created_at,updated_at) VALUES ('nw5','ימי מונדיאל: מה בין כדורגל ובין חינוך ולדורף?','2026-05-08','מאמרים',NULL,NULL,'approved',0,4,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO news (id,title,date,section,summary,link,status,demo,position,created_at,updated_at) VALUES ('nw6','יום הזיכרון לחללי מערכות ישראל ולנפגעי פעולות איבה','2026-04-15','מודעות ופרסומים','אסופת מאמרים ומשאבים.',NULL,'approved',0,5,strftime('%s','now'),strftime('%s','now'));

-- board -> board (1)
INSERT OR REPLACE INTO board (id,title,category,description,region,contact,date,status,demo,position,created_at,updated_at) VALUES ('bd1','ציוד יצירה לכיתת גן — למסירה','ציוד','צמר סרוק, גושי שעווה וקרשי ציור במצב טוב, ממשפחה שילדיה סיימו את הגן.','מרכז','demo@example.com','2026-07-10','approved',1,0,strftime('%s','now'),strftime('%s','now'));

-- jobs -> jobs (1)
INSERT OR REPLACE INTO jobs (id,role,institution,category,region,scope,contact,description,date,status,demo,position,created_at,updated_at) VALUES ('jb1','מחנך/ת כיתה א''','בית ספר ולדורף (דוגמה)','הוראה','צפון','משרה מלאה','jobs-demo@example.com','דרוש/ה מחנך/ת לכיתה א'' לשנת הלימודים תשפ"ז. עדיפות לבוגרי הכשרת ולדורף.','2026-07-01','approved',1,0,strftime('%s','now'),strftime('%s','now'));

-- library -> library (5)
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb1','איך נולדת תקופה?','מאמר','הצצה אל מאחורי הקלעים של עבודת מחנך ולדורף בבניית תקופת לימוד.',NULL,0,0,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb2','"זה היה בחברות"','מאמר','מדריך למחנך להתמודדות עם אלימות ומשחקי נערים בגיל המצווה.',NULL,0,1,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb3','ימי מונדיאל: מה בין כדורגל ובין חינוך ולדורף?','מאמר',NULL,NULL,0,2,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb4','עבודה סמינריונית — הכשרות ולדורף במכללת דוד ילין (דוגמה)','עבודה אקדמית','ייצוג לעבודות הסמינריוניות שנכתבו במסגרות ההכשרה האקדמיות.',NULL,1,3,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb5','עבודת סיום הכשרה לחינוך ולדורף (דוגמה)','עבודת סיום','ייצוג לעבודות סיום של הכשרות לא-אקדמיות ועבודות פנימיות של מחנכים.',NULL,1,4,strftime('%s','now'),strftime('%s','now'));

-- teaching -> teaching (4)
INSERT OR REPLACE INTO teaching (id,title,grp,url,demo,position,created_at,updated_at) VALUES ('tc1','דקלומי בוקר לכיתות א''–ג'' (דוגמה)','סיפורים, שירים ודקלומים',NULL,1,0,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO teaching (id,title,grp,url,demo,position,created_at,updated_at) VALUES ('tc2','דפי ציור צורות — כיתה א'' (דוגמה)','דפי עבודה להדפסה',NULL,1,1,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO teaching (id,title,grp,url,demo,position,created_at,updated_at) VALUES ('tc3','תמונות לתקופת הבניה — כיתה ג'' (דוגמה)','מצגות ותמונות להוראה',NULL,1,2,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO teaching (id,title,grp,url,demo,position,created_at,updated_at) VALUES ('tc4','מקורות לתקופת תולדות האמנות (דוגמה)','חומרי העשרה לתיכון',NULL,1,3,strftime('%s','now'),strftime('%s','now'));

-- forms -> forms (3)
INSERT OR REPLACE INTO forms (id,title,category,description,url,demo,position,created_at,updated_at) VALUES ('fm1','טופס הרשמה לגן ולדורף','הרשמה','טופס הרשמה אחיד לשנת הלימודים.',NULL,1,0,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO forms (id,title,category,description,url,demo,position,created_at,updated_at) VALUES ('fm2','בקשת הצטרפות מוסד לפורום הארצי','בקשות','עבור יוזמות ומוסדות המבקשים ליווי.',NULL,1,1,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO forms (id,title,category,description,url,demo,position,created_at,updated_at) VALUES ('fm3','אישור הורים לפעילות חוץ','אישורים','נוסח מומלץ למוסדות.',NULL,1,2,strftime('%s','now'),strftime('%s','now'));

-- mapPoints -> map_points (21)
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp1','גני ולדורף בירושלים','ירושלים',7,31.778,35.212,'./kinder-list.html',0,0,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp2','גני ולדורף בתל אביב','תל אביב',6,32.075,34.78,'./kinder-list.html',0,1,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp3','גני ולדורף ברמת גן','רמת-גן',6,32.07,34.824,'./kinder-list.html',0,2,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp4','גני ולדורף בפרדס חנה','פרדס חנה',6,32.474,34.97,'./kinder-list.html',0,3,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp5','גני ולדורף בקריית טבעון','קריית טבעון',5,32.716,35.127,'./kinder-list.html',0,4,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp6','גני ולדורף בפתח תקווה','פתח תקווה',5,32.089,34.886,'./kinder-list.html',0,5,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp7','גני ולדורף בכפר הירוק','הכפר הירוק',5,32.135,34.837,'./kinder-list.html',0,6,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp8','גני ולדורף בנס ציונה','נס ציונה',4,31.93,34.798,'./kinder-list.html',0,7,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp9','גני ולדורף בהוד השרון','הוד השרון',4,32.15,34.893,'./kinder-list.html',0,8,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp10','גני ולדורף בבית קשת','בית קשת',4,32.68,35.397,'./kinder-list.html',0,9,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp11','גני ולדורף בבאר שבע','באר-שבע',4,31.252,34.791,'./kinder-list.html',0,10,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp12','גני ולדורף בתעוז','תעוז',3,31.766,34.955,'./kinder-list.html',0,11,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp13','גני ולדורף בעמק חפר','עמק חפר',3,32.343,34.926,'./kinder-list.html',0,12,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp14','גני ולדורף בשוהם','שוהם',2,31.999,34.946,'./kinder-list.html',0,13,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp15','גני ולדורף ברמת השרון','רמת השרון',2,32.146,34.839,'./kinder-list.html',0,14,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp16','גני ולדורף ברחובות','רחובות',2,31.894,34.809,'./kinder-list.html',0,15,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp17','גני ולדורף בציפורי','ציפורי',2,32.753,35.278,'./kinder-list.html',0,16,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp18','גני ולדורף בגדרה','גדרה',2,31.813,34.777,'./kinder-list.html',0,17,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp19','גני ולדורף בגבעתיים','גבעתיים',2,32.072,34.81,'./kinder-list.html',0,18,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp20','גן שירת מדבר — אילת','אילת',1,29.558,34.948,'./kinder-list.html',0,19,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO map_points (id,name,town,count,lat,lng,url,demo,position,created_at,updated_at) VALUES ('mp21','גן ולדורף — שבי ציון','שבי ציון',1,32.982,35.084,'./kinder-list.html',0,20,strftime('%s','now'),strftime('%s','now'));

-- videos -> videos (3)
INSERT OR REPLACE INTO videos (id,title,youtube_id,description,demo,position,created_at,updated_at) VALUES ('vd1','מהו חינוך ולדורף? (דוגמה)',NULL,'סרטון היכרות קצר להורים — יוחלף בסרטון אמיתי של הפורום.',1,0,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO videos (id,title,youtube_id,description,demo,position,created_at,updated_at) VALUES ('vd2','יום בגן ולדורף (דוגמה)',NULL,'מצלמה מלווה בוקר שלם בגן: מעגל בוקר, משחק חופשי ויצירה.',1,1,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO videos (id,title,youtube_id,description,demo,position,created_at,updated_at) VALUES ('vd3','סיור בבית ספר ולדורף (דוגמה)',NULL,'הצצה לכיתות, למרחבי היצירה ולחצר.',1,2,strftime('%s','now'),strftime('%s','now'));

-- podcast -> podcast (3)
INSERT OR REPLACE INTO podcast (id,title,num,date,duration,description,url,demo,position,created_at,updated_at) VALUES ('pd1','למה ולדורף? שיחה עם מחנכת ותיקה (דוגמה)',1,'2026-06-01','42 דק''','פרק פתיחה: שורשי החינוך, ההתפתחות בארץ ומה קורה בכיתה.',NULL,1,0,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO podcast (id,title,num,date,duration,description,url,demo,position,created_at,updated_at) VALUES ('pd2','התפתחות הילד בשבע השנים הראשונות (דוגמה)',2,'2026-06-15','38 דק''','על חיקוי, קצב ומשחק חופשי בגיל הרך.',NULL,1,1,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO podcast (id,title,num,date,duration,description,url,demo,position,created_at,updated_at) VALUES ('pd3','הכשרת מורים — איך נעשים מחנך ולדורף? (דוגמה)',3,'2026-07-01','45 דק''','שיחה עם צוות המכון בירושלים על מסלול ההכשרה.',NULL,1,2,strftime('%s','now'),strftime('%s','now'));

