-- ספריית תוכן: התוכן האמיתי מהאתר הישן, במקום רשומות ההדגמה.
--
-- מקור: mockup/pages/sorting-data/index.json — המלאי שאסף mockup/sorting-content.mjs
-- מ-WordPress REST API של האתר הישן. הכלל: כל פריט ש-migration/url-map.csv מפנה
-- ל-/content-library.html (59 פריטים), בניכוי חמישה שנבדקו אחד-אחד ונפסלו:
--   p2565  ריק, אפס תווים, אין גוף לפוסט
--   p2652  שלוש הרצאות יוטיוב מוטמעות בלבד — מקומן ב-media.html
--   p2318  רשימת קישורים לאתרים חיצוניים — מקומה ב-links.html
--   g1921  כפילות של p2327 (אותו מאמר, גרסת עמוד מול גרסת פוסט)
--   g2087  עמוד הנחיתה של הספר — שימש כמבוא לסעיף בעמוד, לא כפריט ברשימה
-- נשארים 40 מאמרים ו-14 פרקי הספר "חינוך ולדורף – עקרונות ויישומים".
--
-- ה-id שומר את מזהה הפוסט המקורי (lb-p3245), כדי שאפשר יהיה למצוא את הגוף
-- המלא ב-mockup/pages/sorting-data/items/<id>.html ואת ה-URL הישן ב-url-map.csv.
--
-- url נשאר NULL בכוונה: לאתר החדש אין עדיין עמוד-לכל-מאמר (השאלה הפתוחה
-- שמתועדת ב-migration/README.md), וקישור ל-waldorf.co.il היה מת ביום המעבר.
--
-- 52 המאמרים לפי מקצוע (group=subjects) לא נכנסו לכאן: הם תוכנית הלימודים
-- עצמה ו-url-map מפנה אותם ל-curriculum-*.html.

-- רשומות ההדגמה יורדות. מחיקה לפי id ולא TRUNCATE, כדי לא לגעת ברשומות
-- שנוספו מאז דרך ממשק הניהול.
DELETE FROM library  WHERE id IN ('lb1','lb2','lb3','lb4','lb5');
DELETE FROM teaching WHERE id IN ('tc1','tc2','tc3','tc4');
DELETE FROM forms    WHERE id IN ('fm1','fm2','fm3');


-- 40 מאמרים, מהחדש לישן
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3245','רגע היציאה מהכיתה: על אמנות הפרידה בסוף יום לימודים','מאמר','כיצד רגע הפרידה בסוף יום הלימודים משפיע על התלמידים? על חשיבות המעברים, סגירה פדגוגית ואמנות הפרידה בחינוך ולדורף.',NULL,0,0,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3242','אומנות הושבת התלמידים בכיתה','מאמר','סידור מקומות הישיבה בכיתת ולדורף הוא אינו רק עניין לוגיסטי – הוא כלי חינוכי ראשון במעלה. הרצון ליצור ריתמוס נכון ואווירה לימודית תומכת דורש מאיתנו התחשבות רבה: החל…',NULL,0,1,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3240','מבט על פלא החברות ארוכת השנים','מאמר','איך זה קורה שבוגרים ובוגרות שסייימו ללמוד לפני שנים, עדיין בוחרים להעביר את ימי החופש היקרים שלהם יחד מעבר לים? מהו ה"דבק" שנזרע בנפשם ומחזיק מעמד לאורך שנים? מאמר על…',NULL,0,2,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3236','איך נולדת תקופה?','מאמר','מה באמת קורה מאחורי הקלעים של בניית תקופה בחינוך ולדורף? עבור הילדים, התקופה מתחילה כשהמורה נכנס לכיתה ומתחיל ללמד. אבל עבור המחנך היא מתחילה שבועות ואף חודשים קודם לכן.…',NULL,0,3,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3218','זה היה בחברות – מדריך למחנך להתמודדות עם אלימות ומשחקי נערים בגיל המצווה','מאמר','כשבני כיתה ו'' נכנסים מההפסקה חבולים וסוערים, אנחנו המחנכים ניצבים בפני צומת מורכב. האם זו אלימות שיש להעניש עליה, או שפה פנימית של כוחות רצון המחפשים ערוץ לביטוי? במאמר…',NULL,0,4,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3215','ימי מונדיאל: מה בין כדורגל ובין חינוך ולדורף?','מאמר','כדורגל הוא ללא ספק המשחק הפופולרי ביותר בעולם. עבור ילדים רבים, הוא אינו רק פעילות גופנית אלא מרכז הזהות החברתית שלהם, שפה בינלאומית ומושא להערצה. עם זאת, בתוך מסורת…',NULL,0,5,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3201','אחריות אישית: ממושג פילוסופי לפרקטיקה חינוכית ואזרחית','מאמר','מאמר הבוחן את ערך האחריות האישית כגשר בין חירות הפרט למחויבות חברתית. גלו את המתח שבין האתיקה המוסרית לגישה התועלתנית, את הבשורה של האנתרופוסופיה וחינוך ולדורף בטיפוח…',NULL,0,6,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3197','"קבל את הילד ביראה, חנך אותו באהבה ושלחהו לדרכו בחירות"','מאמר','חזון החינוך על פי רודולף שטיינר: בין יראה, אהבה וחירות בשנת 1919, במסגרת הכשרת המורים הראשונה של בית ספר ולדורף, טבע רודולף שטיינר את המשפט שהפך לאבן היסוד של הגישה…',NULL,0,7,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3186','מעבר לעיקול הדרך: מדוע הריקנות של המחנך היא הצלחתו הגדולה ביותר?','מאמר','מאת: ירון זנבל , מרץ 2026 אחרי שנים של מסע משותף, מגיע רגע הפרידה הטעון. מדוע הריקנות שחש המחנך היא בעצם עדות להצלחה חינוכית? ואיך הופכת ה"שמש" הכיתתית ל"ירח" המלווה…',NULL,0,8,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3181','אידיאל המחנך ל-8 שנים בחינוך ולדורף פוגש את המציאות','מאמר','מאת: לינה בטשון מעווד וירון זנבל בבסיס חינוך ולדורף עומד האידיאל של מחנך המלווה את כיתתו לאורך כל שנות בית הספר היסודי (מכיתה א'' ועד ח''). מודל זה מבקש לייצר עבור הילד…',NULL,0,9,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3178','תקופות הלימוד (הבלוקים) בכיתות א''-ט''','מאמר','מאת ירון זנבל, מרץ 2026 תקופות הלימוד (הבלוקים) הן מאבני היסוד של פדגוגיית ולדורף. בשיטה זו, במקום מערכת שעות מקוטעת, התלמידים צוללים לנושא אחד לעומק במשך מספר שבועות…',NULL,0,10,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3169','למידה מרחוק בעת חירום בחינוך ולדורף','מאמר','גם בלמידה מרחוק, חינוך ולדורף נשאר נאמן לעקרונותיו. הלמידה המקוונת בחירום אינה הופכת לדיגיטלית יותר, אלא ל"אנושית יותר" – היא משתמשת בטכנולוגיה כגשר זמני כדי לאפשר לילד…',NULL,0,11,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3164','מקונפליקט לחיבור: ריפוי חברתי באמצעות פרקטיקות בהשראת חינוך וולדורף','מאמר','המאמר, שנכתב בידי אייל בלוך ותום שייפר, מציג מסע מבוסס עקרונות לשיקום חברתי באזורי סכסוך. המאמר מתבסס על שלושה עשורים של עבודה בשטח ומשלב בין הפילוסופיה החינוכית של…',NULL,0,12,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3147','פרדוקס הדיגיטציה בחינוך: בין קדמה טכנולוגית לבין נסיגה קוגניטיבית','מאמר','מאת: ירון זנבל בעוד מערכת החינוך דוהרת לעבר דיגיטציה מלאה תחת ההבטחה להכין את התלמידים למאה ה-21, המציאות בשטח חושפת תמונה הפוכה ומדאיגה. המסכים, שאמורים היו להנגיש ידע,…',NULL,0,13,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3145','מה הטמפרמנט שלי?','מאמר','הרבה לפני שהכרנו את כל החומרים שבטבלה המחזורית, היוונים העתיקים האמינו שהעולם מורכב מ-4 יסודות בסיסיים שיוצרים את כל החומרים שבעולם – אש 🔥, מים 💧, רוח 🌬️ ואדמה ⛰️.…',NULL,0,14,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3139','המהפכה של גיל הנעורים והמענה של חינוך ולדורף','מאמר','מאת ירון זנבל, ינואר 2026 חינוך ולדורף בגילאי חט"ב מבקש לבנות עבור המתבגר "כלי שיט" שייסיע לו במסע המטלטל בין "יבשת" הילדות הבטוחה, לבין "אי" ההתבגרות. דרך שילוב בין…',NULL,0,15,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3137','שברים פשוטים?! אתגרים בהוראת השברים והמענה של חינוך ולדורף','מאמר','מאת ירון זנבל, ינואר 2026 לימוד שברים נחשב לאחת המשימות המאתגרות ביותר במתמטיקה של בית הספר היסודי, עד כדי כך שבעבר הרחוק הם נלמדו רק ברמה האוניברסיטאית – המעבר למספרים…',NULL,0,16,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3134','בין המוביל לבין המאסף: טמפרמנט המחנך כמפת דרכים חינוכית','מאמר','מאת ירון זנבל, ינואר 2026 המאמר מציג את עבודת המחנך דרך המטאפורה של הטיול השנתי, הנעה בין המורה המוביל המקרין ביטחון בראש השיירה למורה המאסף המלווה ברגישות מאחור. דרך…',NULL,0,17,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3130','הערכה מילולית בטווחים: מודדים את בריאות הלמידה','מאמר','מאת: ירון זנבל, דצמבר 2025 אבחון במקום ציון הערכה מבוססת ציון מספרי יוצרת אוטומטית השוואה ודירוג. הבעיה אינה רק הציון עצמו, אלא המסר המוסרי והחברתי שהוא משדר. חינוך…',NULL,0,18,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3112','המסע המחנך: טיולים בחינוך ולדורף','מאמר','לצאת מהכיתה, לפגוש את העולם, להקשיב לדממה ולנשום את הטבע. הטיול בחינוך ולדורף אינו רק מטרה, אלא אמצעי לעיצוב אדם מחובר, המסוגל לאהוב את העולם הרחב. חווית הטיול, המסומנת…',NULL,0,19,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3110','התבוננות בילד: פרקטיקה של הכרה וריפוי','מאמר','מאת: ירון זנבל, נובמבר 2025 מהי ההתבוננות? ההתבוננות בילד היא פרקטיקה פנומנולוגית-רפלקטיבית ושיטה טיפולית המעוגנת בתורתו הביוגרפית-התפתחותית של רודולף שטיינר. בחדר…',NULL,0,20,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3106','בינה מלאכותית בשירות חינוך ולדורף: נתיב לשימוש מושכל','מאמר','האם בינה מלאכותית (AI) מאיימת על עקרונות חינוך ולדורף, או שמא היא כלי הכרחי שיש לרתום? המאמר מתווה נתיב סינרגטי המבחין בין שימוש המורים ב-AI לבין הוראת התלמידים ומציע כי…',NULL,0,21,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3104','השילוב בין אינטואיציות המחנך ובין יכולות AI בליהוק הצגות כיתה','מאמר','הצגת הכיתה בחינוך ולדורף מוגדרת כשיא הפעילות החינוכית של בית הספר והיא מהווה כור היתוך יצירתי, רגשי וחברתי. בהיותה תהליך מורכב, היא מטילה עומס על המחנכים וצוות ביה"ס.…',NULL,0,22,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3099','איך לקבל החלטת גורל','מאמר','כאשר אנו מזהים קושי או צורך בשינוי, והפתרון כרוך בבחירה בין חלופות – אנו עומדים בפני ה צורך לקבל החלטה . אנו נדרשים לקבל החלטות פעמים רבות במהלך חיינו – לצד החלטות…',NULL,0,23,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3086','מדריך לכריכת מחברות תקופה לספר השנה','מאמר','מחברת התקופה בחינוך ולדורף היא אמצעי מרכזי לתיעוד תהליך הלמידה שמתרחש במהלך תקופות הלימוד. כל מחברת כוללת סיכומים בכתב, ציורים, סיפורים, שירים וכתיבה אישית של התלמיד.…',NULL,0,24,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3088','התפתחות פיזית ונפשית בשלושת השביעונים הראשונים','מאמר','האדם נתפס כמורכב מארבעה גופים: הגוף הפיזי, הגוף האתרי, הגוף האסטרלי והגוף הרוחי. כל אחד מהם קשור לתחומים שונים של ההוויה האנושית ופועל ברמות שונות של קיום. בחינוך ולדורף…',NULL,0,25,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p3020','הפוך גוטה. הפוך','מאמר','המאמר משווה בין שתי מערכות גדולות – בנקאית וחינוכית – ומנתח את ניסיונותיהן ליישם טכנולוגיה מתקדמת. במערכת הבנקאית, ניסיון להחליף סניפים מסורתיים במערכת מתוקשבת עתידנית…',NULL,0,26,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2851','המעגל בחינוך ולדורף','מאמר','המעגל בחינוך ולדורף – עיבוד של המאמר " Why do we have Circle Time throughout the Grades? " שכתבה Kolea Quincey מתוך WaldorfToday בחינוך ולדורף נהוגה ושגורה העבודה עם…',NULL,0,27,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2810','תקופות בוטניקה בכיתות ה''-ו'': לצמוח עם הילדים','מאמר','מפשוט למורכב, מרך למעוצב, מדמיוני למציאותי, מתלות לעצמאות. התבגרות. יא וַיֹּאמֶר אֱלֹהִים, תַּדְשֵׁא הָאָרֶץ דֶּשֶׁא עֵשֶׂב מַזְרִיעַ זֶרַע, עֵץ פְּרִי עֹשֶׂה פְּרִי…',NULL,0,28,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2803','לספר סיפורים (בע"פ) בחינוך ולדורף','מאמר','חינוך ולדורף מושתת על סיפור סיפורים. מהסיפור במעגל בגן הילדים ועד שיעורי המדעים בתיכון. ולא סתם סיפור – הכוונה היא לסיפור בעל פה, ללא ספר. מדוע הסיפור בחינוך ולדורף כה…',NULL,0,29,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2665','תפקיד מנהל בית הספר, ניהול משותף, מנהיגות ואחריות בבית ספר ולדורף','מאמר','אפריל 2020 הקדמה המאמר נשען על חומרים שונים מעולם המנהיגות האופקית. העריכה שלו נעשית בפסח, בתקופת הקורונה. בתקופה זו המתח שבין כוחות עבר ועתיד מתחדד. הדרישה להתחדשות…',NULL,0,30,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2650','למידה מרחוק מתוך השקפת חינוך וולדורף','מאמר','מאת: Martyn Rawson תרגום: גיא פרי הקדמה בהינתן העוצר הנוכחי והצורך הכפוי בלמידה מרחוק, מהבית, כדאי להקדיש זמן לחשיבה מחודשת של עקרונות הלמידה על פי השקפת חינוך וולדורף.…',NULL,0,31,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2591','הכיתה כמרחב להתחנכות','מאמר','או הדרך הפנימית של מורה הכיתה מאת: אורי עברי פורסם ב אדם עולם באביב 2013 שתי סיבות מביאות אותי לכתוב מאמר זה על דרכו הפנימית של המורה. ראשית, כמורה וותיק יחסית מצאתי…',NULL,0,32,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2585','על שאלות חינוכיות בגיל ההתבגרות המינית (כיתות ו'', ז'', ח''): ליווי חינוכי וחינוך מיני','מאמר','מבוא זה זמן רב שהשאלה כיצד נכון ללוות את שלב ההתעוררות של נערות ונערים לזהותם האישית בגיל טרום הנעורים (כיתות ז-ח) חייה בתוכי. האם ההנחיות ששטיינר נתן בהתייחסו ללווי…',NULL,0,33,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2398','הקולגיום','מאמר','מאמר זה מציע תפיסה כללית לבניית ישיבות צוות. במונח צוות אפשר להכליל מחלקה, ענף גם כל העובדים של ארגון לא גדול , למשל עד 60-70 משתתפים. הדוגמא וההשראה מתבססות על ישיבת…',NULL,0,34,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2391','זו לא התורה כולה – חינוך ולדורף ויהדות','מאמר','שטיינר דיבר על רליגיוזיות כרגש עמוק של הכרת תודה, ממשיכיו בחינוך ולדורף מתייחסים ללאומיות כבסיס לתחושת שייכות. כיצד משלבים יהדות וציונות בלימודי ולדורף בישראל? הרב…',NULL,0,35,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2325','עיצוב מרחב פיזי ברוח החינוך','מאמר','תכנון מבנה גן ילדים ולדורף בהרדוף האם וכיצד ניתן לתכנן מבנה כך שיוכל לתמוך בפעילויות חינוכיות, באווירה חינוכית ובערכים חינוכיים מסוימים? כיצד אפשר לחבר בין תכנון אדריכלי…',NULL,0,36,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2328','חינוך ולדורף ואתגרי הזמן','מאמר','מאת: אורי עברי [המאמר ב קובץ word ] הציטוטים מובאים מתוך סדרת ההרצאות של שטיינר שנקראות בעברית "חינוך וחיים רוחיים מודרנים" ואשר ניתנו כבסיס לייסוד חינוך ולדורף באנגליה.…',NULL,0,37,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2327','דרכו הפנימית של המורה או "חנוך לנער לפי דרכו"','מאמר','מאת: אורי עברי [המאמר כ קובץ word ] שתי סיבות מביאות אותי לכתוב מאמר זה על דרכו הפנימית של המורה. ראשית כמורה בשבתון מצאתי עצמי מלווה מורים עמיתים בדרכם ומתוך עבודתי עלו…',NULL,0,38,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2323','22 שאלות ותשובות על חינוך ולדורף','מאמר','מה מיוחד בבית ספר ולדורף? הרושם הראשון שמקבלים מהנעשה בבית ספר יסודי ברוח חינוך ולדורף הוא של פעילות אמנותית מתמשכת: הילדים שרים, מנגנים, רוקדים, מציירים, רושמים,…',NULL,0,39,strftime('%s','now'),strftime('%s','now'));

-- 14 פרקי הספר "חינוך ולדורף – עקרונות ויישומים", מורי בית הספר ולדורף הרדוף, סתיו 2000
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2038','א. מבוא','ספר','הספר "חינוך ולדורף – עקרונות ויישומים" נכתב על-ידי מורי בית הספר ולדורף הרדוף, סתיו 2000 הדברים שיובאו לעיל מנסים להציג את חינוך ולדורף כפי שהוא התפתח ומיושם בבתי הספר…',NULL,0,100,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2042','ב. יסודות חינוך ולדורף','ספר','חינוך ולדורף נוסד בתחילת המאה על-ידי המחנך, הפילוסוף והוגה הדעות רודולף שטיינר (1861-1925). בית-הספר הראשון הוקם כבית-ספר לילדי פועלים במפעל "ולדורף-אסטוריה" בעיר…',NULL,0,101,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2045','ג. בתי-ספר ולדורף בארץ','ספר','בארץ פועלים כיום שלשה בתי- ספר ולדורף: בירושלים – בי"ס "אדם", עם תשע כיתות, א'' עד ט''; בטבעון – בי"ס "שקד", עם שמונה כיתות א'' עד ח''; ובי"ס ולדורף הרדוף, בקיבוץ הרדוף…',NULL,0,102,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2047','ד. ניהול בית-הספר ועבודת המורים','ספר','כאשר התבקש רודולף שטיינר (מייסד חינוך ולדורף) לעזור בהקמת בית-הספר ולדורף הראשון (1919), הוא אסף סביבו קבוצת מורים וניסה להכשירם להוראה בתקופה הקצרה שעמדה לרשותם עד…',NULL,0,103,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2051','ה. עבודה עם הורים – מעורבות הורים','ספר','השותפים הישירים להוויית החיים הבית-ספרית הנם הילדים, המורים וההורים. כאשר מנסים ליצור איכויות שהנן מעבר להקניית ידע ואינפורמציה, עולה שאלת החיים המשותפים בקהילת…',NULL,0,104,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2054','ו. על כמה צדדים מעשיים','ספר','בפרקים הבאים יעשה הניסיון להביא בקיצור כמה מן הצדדים המעשיים של העבודה הפדגוגית בבית-הספר. בכל תאור צריך רק לקחת בחשבון, שאת הדברים החשובים ובעלי המשמעות אין אפשרות לתאר…',NULL,0,105,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2059','ז. מחיי הכיתה – כמה דוגמאות למתודות ההוראה','ספר','בפרק זה יובאו כמה דוגמאות מעבודה של כיתות שונות בבתי-הספר ולדורף בארץ. בהביאנו דוגמאות מהעבודה המעשית של חיי בית-הספר יש לזכור שבבית-ספר ולדורף אין דרך אחת ויחידה ללמד…',NULL,0,106,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2061','ח. סמכות וחופש – שאלת הדמוקרטיה בחינוך ולדורף','ספר','הדמוקרטיה הפכה בעת החדשה, ובמיוחד במאה ה- 20 לאחד מהערכים המרכזיים של התרבות המערבית. אולם הדמוקרטיה אינה תופעה מובנת מאליה בתולדות האנושות. את רובה הגדול של עברה עשתה…',NULL,0,107,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2062','ט. הערכה בחינוך ולדורף','ספר','תהליכי הערכה נכונים אינם מנותקים מהתהליך החינוכי אותו הם אמורים להעריך. תהליכי הערכה מנותקים וכביכול אוביקטיביים אינם חלק מהתהליך הלימודי אליו שואף בית-ספר ולדורף. כמו…',NULL,0,108,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2063','י. הכשרת המורים ברוח חינוך ולדורף – סמינר המורים','ספר','המורים המלמדים בבית-הספר עברו כולם (או שעדיין עוברים במקביל לעבודתם) הכשרת מורים ברוח חינוך ולדורף. הכשרה זו נמשכת כשלוש שנים ומהווה תנאי לקבלת המורה לעבודה בבית-הספר.…',NULL,0,109,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2064','יא. כמה צדדים טכניים','ספר','א. מעמד חוקי והכרה בתי-ספר ולדורף בארץ הוכרו כבתי-ספר ממלכתיים, רשמים במסגרת משרד החינוך. בתי-הספר מקבלים את התקציבים המגיעים לכל בית-ספר ונתונים לאותו פיקוח. עקב אופיים…',NULL,0,110,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2065','יב. אנשים שונים אודות חינוך ולדורף','ספר','"אם היה לי ילד בגיל בית-ספר, הייתי שולחו לאחד מבתי-הספר ולדורף" סול בלו – סופר וחתן פרס נובל לספרות "רוב הילדים שמתחנכים במסגרת חינוך ולדורף הנם שמחים, נבונים, מקבלים,…',NULL,0,111,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2066','יג. מדברי תלמידים בתיכון ולדורף הרדוף על בית ספרם','ספר','" … כאן זה לא רק כיף לי, ולא רק שהכל כה שונה, אלא כאן לומדים קשה ועובדים, אך יחד עם זה מאד נהנים. כאן אנחנו חיים בתוך הדרך שבה אנו רוצים לחיות." תלמידה בכיתה י'' "בבית…',NULL,0,112,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,demo,position,created_at,updated_at) VALUES ('lb-p2067','יד. שירים ודקלומים מעבודות התלמידים','ספר','שיר המשאלה יש לי משאלה היא קטנה וגם גדולה שיהיה שלום בין ארצות ושיהיה שלום בין אחים ואחיות שנדע לאהוב כל אדם ואדם למרות שאף אחד לא מושלם. יש לי משאלה היא קטנה וגם גדולה…',NULL,0,113,strftime('%s','now'),strftime('%s','now'));
