-- ספריית תוכן: 50 העבודות שנשארו מחוץ לארכיון, והקישור לעמוד של כל פריט.
--
-- מה התגלה: 51 הפריטים בקטגוריה "עבודות גמר" באתר הישן אינם עבודות הגמר של
-- תלמידי י"ב. הם עבודות אקדמיות על חינוך ולדורף — חציון 32,839 תווים, הארוכה
-- 134,204, ל-46 מהן יש שם מחבר. url-map.csv מפנה אותן ל-curriculum-capstone.html
-- בגלל התנגשות שם בלבד: אותו עמוד עוסק בפרויקט הגמר של כיתה י"ב, נושא אחר לגמרי.
-- הן שייכות לספריית תוכן, והן בדיוק שלוש תת-הקטגוריות שהעמוד מתאר.
-- p2337 יצא מהרשימה — זהו הספר "חינוך ולדורף – עקרונות ויישומים" בשנית.
--
-- הסיווג לשלוש תת-הקטגוריות נקרא מעמוד השער של כל עבודה, במקום שבו עבודת תזה
-- מציינת את התואר ועבודה סמינריונית את שם הקורס והמנחה. ל-10 עבודות אין הצהרה
-- כזאת, והן מסומנות 'עבודה' — סיווג שהפורום צריך להשלים, לא לנחש עבורו.
--
-- כל 104 הפריטים מקבלים url לעמוד הייעודי שלהם (lib-<id>.html), שנוצר על ידי
-- mockup/library-pages.mjs מהגוף השמור ב-sorting-data/items/.
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3204','כיצד באות לידי ביטוי תפיסות מקדמות בריאות בפרקטיקות הפדגוגיות היומיומיות של בתי ספר וולדורף?','עבודה סמינריונית','עבודה סמנריונית | מגישים: כרמי שרון ונבו עמית מרצה : ד"ר גלעד גולדשמידט עבודה זו בוחנת את הקשר בין חינוך וולדורף לבין קידום בריאות באמצעות סקירת ספרות מקיפה. שאלת המחקר…','./lib-p3204.html',NULL,'2026',0,0,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3045','כיצד ערך הפליאה בא לידי ביטוי בחינוך ולדורף בבית ספר יסודי?','עבודה','"מדוע מבקשת נפש האדם אחר הכרת העולמות העליונים? מכיוון שכל מבט החדור ברגש פליאה אל עולם החושים, נהיה לשאלה רוויית כמיהה אודות הוויית הרוח." – רודולף שטיינר, מדיטציות…','./lib-p3045.html','יעל גלמונד מנדל','2025',0,1,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3040','סמכות אוהבת – על הסמכות בחינוך ולדורף','עבודה סמינריונית','המחנך כירח במקום המחנך כשמש כיצד מחנכים בחינוך וולדורף מבססים "סמכות אוהבת" בכיתות ה''-ח''. שם הקורס: רגשות בחינוך תשפ״ד המרצה: ד״ר אילנית פינטו דרור מגישה: אלה גבריאלי…','./lib-p3040.html','אלה גבריאלי','2025',0,2,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2939','תיאטרון בובות בביה"ס היסודי','עבודה של מורי ולדורף','סמינר וולדורף – זומר רמת גן , 2012 הקדמה לפני כ-7 שנים למדתי קורס תיאטרון בובות ככלי טיפולי חינוכי. אינני זוכרת מדוע נמשכתי ללמוד דווקא את הקורס הזה, אולם מאז נשאר התחום…','./lib-p2939.html','נגה יצחקי','2023',0,3,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2938','עיון בקוריקולום התרבותי-היסטורי בחינוך וולדורף','עבודה של מורי ולדורף','סמינר וולדורף "זומר" סיון ה''תשע"ד; יוני 2014 הקדמה בשנת 2002 זכיתי לבקר בברזיל. בין שלל הרפתקאותי שם, זכיתי גם לבקר בעיר רסיפה (Recife) בצפון-מזרח ברזיל – בנקודה הקרובה…','./lib-p2938.html','יפתח שילוני','2023',0,4,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2940','חינוך וולדורף כפלטפורמה לשימור הזמר העברי המוקדם','עבודה','נובמבר 2014 מבוא – הזמר העברי ניתן לציין את תחילתו של הזמר העברי סביב תחילתה של העליה הראשונה בשנת 1882, וסביב אווירת התחייה הלאומית ששררה סביבה. בסופה של המאה ה-19…','./lib-p2940.html','חנה טל אליאן','2023',0,5,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2911','בשלות לכיתה א''','עבודה','שאלת המחקר של עבודה זו עוסקת בתנאים שצריכים להתקיים על מנת שהיתרונות של החינוך האנתרופוסופי יבואו לידי ביטוי בכלל, ובהקשר של בשלות של ילד בכיתה א''. כאשר שאלת המחקר…','./lib-p2911.html','מישל איבל','2022',0,6,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2903','המעגל בבית הספר היסודי','עבודה של מורי ולדורף','פרויקט אישי במסגרת שנת השתלמות שירה-פז-המעגל-בבית-ספר-יסודי הורד תוכן עניינים מבוא עקרונות התפתחותיים בחינוך ולדורף מהו המעגל המעגל בגן המעגל בבית הספר היסודי המעגל…','./lib-p2903.html','שירה פז','2022',0,7,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2894','מה הם הטמפרמנטים ע"פ שטיינר וכיצד הם משתלבים בעבודה החינוכית בחינוך ולדורף?','עבודה סמינריונית','סמינריון בחינוך מנחה: גלעד גולדשמידט תאריך: 2.10.2022 טמפרמנטים-בחינוך-ולדורף-אור-טימור-אזולאי-אתר הורד מבוא בעבודה זו ואעסוק בנושא ארבעת הטמפרמנטים של האדם. אסקור את…','./lib-p2894.html','אור טימור-אזולאי','2022',0,8,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2847','מקומו של חינוך וולדורף בתוך מערכת החינוך הממלכתי בישראל','עבודה','תפיסות אנשי.ות חינוך מובילים מהקהילה האנתרופוסופית עבודת-גמר-יעל-הרן הורד תקציר מחקר זה עסק בשאלת חיבורו של חינוך ולדורף למערכת החינוך הממלכתי בישראל. בירור שאלה זו…','./lib-p2847.html','יעל הרן','2022',0,9,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2841','הקשר בין חינוך ולדורף ובין שהיה בטבע','עבודה','בעבודה זו אחקור את הקשר בין חינוך ולדורף לבין שהייה בטבע. האם וכיצד יכולים להתחבר, מהם קווי הדימיון והשוני. בפרק הראשון אסקור את מהותו ודרכו של חינוך ולדורף ואתאר את…','./lib-p2841.html','שגית סגל','2022',0,10,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2833','תפיסות של מחנכים במסגרות חינוך ולדורף לגיל הרך את העבודה הרפלקטיבית  שלהם בהקשר לעבודת הצוות','עבודה','תקציר העבודה בגן ילדים בישראל, בו יש עד 35 ילדים ומספר אנשי צוות מעורבים בו, היא משימה רחבת היקף הטומנת בחובה מגוון של מרכיבים. במהלך יום בגן הגננת נדרשת לפעול בתוך שדה…','./lib-p2833.html','עפר גן אור','2022',0,11,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2812','לאן נושבת הרוח? סוגיות ביישום אלמנטים מחינוך וולדורף בתלמוד תורה חרדי','עבודה לתואר שני','עבודת גמר מחקרית (תזה) המוגשת לאחר קבלת התואר "מוסמך" אוניברסיטת חיפה, הפקולטה לחינוך, החוג למנהיגות ומדיניות בחינוך בהנחיית: ד"ר דבורה גולדן…','./lib-p2812.html','גיורא אבידור','2022',0,12,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2764','העקרונות הפדגוגיים של החינוך האנתרופוסופי בגיל הרך','עבודה לתואר שני','מכללת אורנים, הפקולטה ללימודים מתקדמים עבודת גמר מוגשת כחלק מחובות הלימודים לתואר M.Ed, בתוכנית לחינוך בגיל הרך מגיש: כרמי ינון בהנחיית דר'' סיגל אחיטוב אוגוסט 2021 |…','./lib-p2764.html','כרמי ינון','2021',0,13,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2760','אמנות החינוך ומלאכת החיים: חשיבותה ומשמעותה של האמנות בחינוך ולדורף','עבודה סמינריונית','מכללת דוד ילין מסלול הוראה בחינוך ולדורף עבודה סמינריונית בחינוך מנחה: דוקטור גלעד גולדשמידט אוקטובר 2021 מבוא ראשיתו של הרעיון להקדיש את עבודת הסמינריון שלי לאמנות…','./lib-p2760.html','נגה הראל','2021',0,14,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2758','מהם ארבעת הטמפרמנטים וכיצד עובדים איתם בבית ספר ולדורף?','עבודה סמינריונית','מנחה: ד"ר גלעד גולדשמיט מגישה: חייקי לביא תאריך הגשה: אוקטובר 2021 מבוא בעבודה זו ברצוני להציג בהרחבה את ארבעת הטמפרמנטים בהקשר של עבודה עם ילדים בבית ספר ולדורף. שאלת…','./lib-p2758.html','חייקי לביא','2021',0,15,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2755','עבודת העץ בתיכון ולדורף','עבודה סמינריונית','גיא-כהן-עבודת-עץ-בתיכון-ולדורף הורד סמינריון בחינוך וולדורף המרצה: גלעד גולדשמידט מגיש: גיא כהן מור תאריך 3.4.2021 כ״א בניסן ה׳תשפ״א הקדמה מאז ומתמיד אהבתי את עבודת העץ.…','./lib-p2755.html','גיא כהן','2021',0,16,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2745','כיצד מתמודד בוגר בית ספר וולדורף עם החיים הבוגרים שלאחר סיום בית הספר?','עבודה סמינריונית','שם: ליה סילברברג מוסד: דוד ילין מנחה: גלעד גולדשמידט מבוא עבודה זו מתמקדת בחייהם הבוגרים של יוצאי חינוך ולדורף כאשר שאלת המחקר היא כיצד מתמודד בוגר בית ספר ולדורף עם…','./lib-p2745.html','ליה סילברברג','2021',0,17,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2741','אפיון וניתוח התרבות הארגונית בבית ספר ולדורף','עבודה סמינריונית','מרצה: גלעד גולדשמידט מגיש: אסף אשל תאריך: ינואר 2021 מבוא מזה ארבע שנים שאני מחנך כיתה בבית ספר עודד השוכן ביישוב יודפת במועצה האזורית משגב. בתחילת דרכי התוודעתי לתרבות…','./lib-p2741.html','אסף אשל','2021',0,18,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2733','כיצד מורים בחינוך ולדורף מתמודדים עם הפרעת קשב וריכוז בקרב ילדים בבית ספר יסודי','עבודה סמינריונית','פסיכופדגוגיה בכיתה כיצד מורים בחינוך ולדורף מתמודדים עם הפרעת קשב וריכוז בקרב ילדים בבית ספר יסודי מחקר איכותני במסגרת מטלה סמינריונית החוג לחינוך במכללת "אורנים" מוגש…','./lib-p2733.html','שקד אליאס','2021',0,19,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2726','תרומתה וחשיבותה של הוראת השפות הזרות בכיתות א''-ב'' בחינוך ולדורף','עבודה סמינריונית','עבודה סמינריונית בחינוך מגישה דפני ססיל ליטמן כהן מוגש לד"ר גלעד גולדשמידט החוג לחינוך ולדורף – מכללת דוד ילין שנה"ל תש"פ "מטרתנו היא לפתח את הילד באופן כזה שהוא יוכל…','./lib-p2726.html','דפני ססיל ליטמן כהן','2021',0,20,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2700','כיצד תומכת תוכנית הלימודים ברישום צורה בבית הספר היסודי את התפתחות הילד?','עבודה','בעבודה זו אעסוק בנושא רישום צורה-מקצוע ייחודי לבתי ספר וולדורף. אשאל את השאלה כיצד תוכנית הלימודים ברישום צורה בבית הספר היסודי מתכתב עם התפתחות הילד על פי שטיינר. בפרק…','./lib-p2700.html','אומר אהרון','2020',0,21,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2690','פתיחת בוקר בעבודה בחווה','עבודה סמינריונית','מכללת דוד ילין מסלול מחנכי וולדורף סמינריון בחינוך 1029907-26 , תש"פ. מרצה: גלעד גולדשמידט מנחה אישי: איתי פז (ז"ל), גיל קינן בעבודה זו אנסה לבחון את שאלת פתיחת יום…','./lib-p2690.html','עמית גל','2020',0,22,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2692','סיפורת והתפתחות הילד','עבודה סמינריונית','כיצד מלווה ותומכת הסיפורת את התפתחות הילד בתוכנית הלימודים של בית ספר וולדורף? עבודה מסכמת בקורס "סמינריון חינוך" מנחה: גלעד גולדשמידט השנה לימדתי קורס בנושא סיפורת…','./lib-p2692.html','דוד בניהו','2020',0,23,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2680','מקומה של האסתטיקה בחינוך ולדורף','עבודה סמינריונית','מגישה: אורי גלעדי מנחה: דר'' גלעד גולדשמידט מתוך המבוא לעבודה: ''עלינו להדגיש שוב ושוב, שתפיסת העולם האנתרופוסופית מטפחת תודעה – שבין תחומי האמנות, הדת והמדע – שוררים יחסי…','./lib-p2680.html','אורי גלעדי','2020',0,24,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2586','הומור בחינוך האנתרופוסופי','עבודה סמינריונית','סמינריון בחינוך, מכללת דוד ילין מנחה: ד"ר גלעד גולדשמידט מגישה: שרה מלכה מרץ 2020 הקדמה בחרתי לעסוק בעבודה זו בנושא ההומור, מכיוון שמשחר ילדותי אני זוכרת כיצד ההומור…','./lib-p2586.html','שרה מלכה','2020',0,25,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2574','משמש לירח: משימת ההתפתחות של המחנך','עבודה סמינריונית','עבודה סמינריונית בחינוך מאת: שרון הררי מנחה: ד"ר גלעד גולדשמידט המכללה האקדמית לחינוך ע"ש דוד ילין תש"פ, 2020 עשרת הדברות / יהודה עמיחי אָבִי הָיָה אֱלהִים וְלא יָדַע.…','./lib-p2574.html','שרון הררי','2020',0,26,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2567','הקניית כתיבה וקריאה בבית ספר ולדורף','עבודה סמינריונית','סמינריון בנושא: הקניית כתיבה וקריאה בבית ספר ולדורף , דצמבר, 2019 מבוא בעבודה זו נעשה ניסיון לבחון את תפיסותיו של החינוך האנתרופוסופי ביחס להקניית מיומנויות הקריאה, כפי…','./lib-p2567.html','זהר פלג','2019',0,27,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2550','חינוך מיני בגישת ולדורף','עבודה סמינריונית','כיצד יכולה גישת ולדורף לחינוך לחנך ילדים ובני נוער למיניות בריאה? מנחה: ד"ר גלעד גולדשמידט המכללה האקדמית לחינוך ע"ש דוד ילין אוקטובר 2019 מבוא מהו חינוך מיני? מעבר…','./lib-p2550.html','סתיו אברהמי','2019',0,28,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2545','הומור וחינוך ולדורף','עבודה','מתוך ההקדמה: הבחירה לעסוק בעבודה זו בנושא ההומור, ובעיקר הומור בקרב אנשי חינוך בחינוך ולדורף , הגיעה אליי מתוך ההבנה כי לאורך לימודיי בחינוך ולדורף נדמה היה כי מעולם לא…','./lib-p2545.html','ליאת אדלר','2019',0,29,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2540','האידאולוגיה הרביעית? – חינוך ולדורף בראי שלוש אידאולוגיות העל','עבודה סמינריונית','באיזה אופן משקף חינוך ולדורף את שלוש אידאולוגיות העל? לקריאת עבודת הסימנריון של מי-טל רחמני','./lib-p2540.html','מי-טל רחמני','2019',0,30,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2536','חינוך לאורינות מדיה בחינוך ולדורף','עבודה לתואר שני','Education for Media Literacy Media in Waldorf education','./lib-p2536.html',NULL,'2019',0,31,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2526','כיצד תומך תהליך ההצגה בכיתה י'' בחינוך ולדורף בהתפתחות הילד','עבודה סמינריונית','עבודה סמינריונית בקורס: סמינריון בחינוך (מורים בפועל מחזור ב'') – 1029901-26, תשע"ח מרצים: ד"ר גלעד גולדשמידט וד"ר בועז צבר מגיש: זיו רייטר 15.08.2019 תוכן עניינים מבוא…','./lib-p2526.html','זיו רייטר','2019',0,32,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2525','חינוך ולדורף כחינוך הומניסטי','עבודה סמינריונית','מנחה: ד"ר גלעד גולדשמידט מגיש: גל אשל אוגוסט 2019 תוכן עניינים מבוא פרק ראשון – הומניזם פרק שני – חינוך ולדורף רודולף שטיינר אנתרופוסופיה מהות החינוך חלוקה לשלוש תקופות…','./lib-p2525.html','גל אשל','2019',0,33,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2522','שנים עשר החושים לאור האנתרופוסופיה ומשמעותם לחינוך','עבודה','העבודה עוסקת בתפיסת שנים עשר החושים על פי מדע הרוח האנתרופוסופיה. חינוך ולדורף על פי – משנתו של ד"ר רודולף שטיינר שחקר את התפתחות האדם והאנושות בראי מדע הרוח והטבע, עוסק…','./lib-p2522.html','רעות אתרוגי','2019',0,34,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2519','האם תכנית הלימודים במדעים בכיתות ו'' ז'' ח'' בבתי ספר ולדורף הולמת את התפתחות הילד? ואם כן כיצד?','עבודה סמינריונית','העבודה נכתבת במסגרת הכשרת מורי ולדורף במכללת דוד ילין. מכיוון שאני עוסק בהוראת המדעים ומחנך כיתה בבי"ס יחיאל, בי"ס ולדורף בטל שחר, בחרתי לעסוק בהוראת המדעים. לפעמים נדמה…','./lib-p2519.html','תום נוימן','2019',0,35,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2479','האם  וכיצד עקרונות יסוד מתוך הפסיכולוגיה החיובית באים לידי ביטוי בחינוך וולדורף בשביעון השני','עבודה סמינריונית','מכללת דוד ילין עבודת סמינריון [ להורדת העבודה כקובץ PDF ] מנחים: ד"ר גלעד גולדשמידט ד"ר בועז צבר מגיש: יובל קפל 07/3/2019 "שאיפתנו העליונה היא לפתח בני אדם חופשיים,…','./lib-p2479.html','יובל קפל','2019',0,36,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2411','דרכים ליישום החינוך העמלני באמצעות עבודת אדמה','עבודה סמינריונית','עבודת סמינריון דרכים ליישום החינוך העמלני באמצעות עבודת אדמה. התנסותי כמורה במסגרת הקמת חווה חקלאית בבית הספר האנתרופוסופי "עליה" בבת גלים. מוגש על ידי: עמיר פרי…','./lib-p2411.html','עמיר פרי','2018',0,37,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2410','מה בין חינוך ולדורף לבין החינוך ''מבוסס-טבע'' בעבודת גן הילדים','עבודה סמינריונית','המכללה האקדמית לחינוך ע"ש דוד ילין סמינריון בחינוך (ולדורף מורים בפועל מחזור ב'') תשע"ח עבודה סמינריונית בנושא: מה בין חינוך ולדורף לבין החינוך ''מבוסס-טבע'' בעבודת גן…','./lib-p2410.html','אביב קידר','2018',0,38,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2389','התאמות בחינוך ולדורף – השוואה בין מאפייני חינוך ולדורף חילוני לבין דתי יהודי','עבודה סמינריונית','סמינריון: התאמות בחינוך ולדורף – השוואה בין מאפייני חינוך ולדורף חילוני לבין דתי יהודי מאת: ענת עציץ בעבודה זו ברצוני לבדוק כיצד התאוריה החינוכית של ולדורף באה לידי…','./lib-p2389.html','ענת עציץ','2018',0,39,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2372','הוראת המוזיקה בשנים הראשונות בבית ספר ולדורף','עבודה סמינריונית','מאת: מוטי עמיר במסגרת קורס: סמינריון בחינוך (ולדורף מורים בפועל מחזור ב'') המרצים: ד"ר בועז צבר, ד"ר גלעד גולדשמיט ״כל אדם מסוגל ליצור, וכן מסוגל כל ילד ליצור, באשר כושר…','./lib-p2372.html','מוטי עמיר','2018',0,40,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2357','כיצד לימודי האומנות הפלסטית בתיכון ולדורף תומכים בהתפתחות הנוער? | עפרה קנה','עבודה סמינריונית','עבודה סמינריונית מנחה: דר'' גלעד גולדשמידט מגישה: עפרה קנה עפרה קנה אומנות בבית ספר ולדורף תיכון [העבודה כקובץ word] מבוא במציאות של ימינו הנחות היסוד המתבססות על ידע…','./lib-p2357.html',NULL,'2018',0,41,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2353','סמכות המחנך בחינוך ולדורף','עבודה סמינריונית','עבודה סמינריונית בחינוך מאת אשר וזה מנחה: ד"ר גלעד גולדשמידט סמינריון בחינוך סמכות המורה [העבודה כקובץ word] תוכן העניינים מבוא כללי פרק ראשון: סקירה כללית של סמכות…','./lib-p2353.html','אשר וזה','2018',0,42,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2347','פיסול בחינוך וולדורף – הלכה למעשה על הקשר שבין פיסול לחיזוק כוחות הרצון','עבודה סמינריונית','עבודת סמינריון מאת רעות לביא מנחים: בועז צבר, גלעד גולדשמידט בעבודה זו אציג את כלי העבודה הנפלא של פיסול חינוכי בחינוך וולדורף, וכיצד תורם ותומך את התפתחות הילד בשלבי…','./lib-p2347.html','רעות לביא','2018',0,43,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2349','חינוך ולדורף וחינוך יהודי – "הילכו שניהם יחדיו?"','עבודה סמינריונית','מאת ינון קמון מנחה: ד"ר איתן שיקלי תאריך: אפריל 2018, ניסן תשע"ח חינוך ולדורף וחינוך יהודי – "הילכו שניהם יחדיו?" מהן הזיקות וקווי המתאר המשותפים לחינוך ולדורף בישראל…','./lib-p2349.html','ינון קמון','2018',0,44,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2339','מימוש פילוסופית החינוך האנתרופוסופי במבני חינוך ולדורף','עבודה סמינריונית','סמינריון תמטי בחינוך וארכיטקטורה מגישים: יהלי קפל ואיתמר נייגר // שנה אקדמית ד'' // התשע"ד מנחים: ד"ר איתן מכטר וד"ר ליאורה ברעם-שחל ארכיטקטורה וחינוך ולדורף','./lib-p2339.html','יהלי קפל ואיתמר נייגר','2018',0,45,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2341','כיצד תומכים המבנים שבהם שוכנים בתי ספר וגני וולדורף בפעילות החינוכית המתרחשת בתוכם?','עבודה סמינריונית','עבודה סמינריונית בחינוך מאת עדי בלוכביץ מנחים: ד"ר גלעד גולדשמידט, ד"ר בועז צבר עבודה סמינריונית על אריכטקטורה של בתי ספר ולדורף (כולל איורים כקובץ word) מבוא כאשר…','./lib-p2341.html','עדי בלוכביץ','2018',0,46,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2338','האם וכיצד נותן חינוך וולדרוף מענה לילדים אשר חוו טראומה בילדותם?','עבודה סמינריונית','עבודת סמינריון מאת עידן יהב מנחים: גלעד גולדשמידט ובועז צבר מבוא נושא המחקר של עבודתי הוא : האם וכיצד נותן חינוך וולדרוף מענה לילדים אשר חוו טראומה בילדותם? אל השאלה…','./lib-p2338.html','עידן יהב','2018',0,47,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2320','על סינתזה ואנליזה בהוראת המתמטיקה בחטיבת הביניים','עבודה','מאת: ניצן פריימן הקדמה חיבור זה נכתב בעיקר עבור מורי מתמטיקה בכיתות ז'' ח'', אך אני מאמין כי ניתן לפתח את הכיוונים שאביא בו גם עבור הוראת המתמטיקה בכיתות הצעירות יותר.…','./lib-p2320.html','ניצן פריימן','2018',0,48,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2319','התפתחות לימודי השירה והמוזיקה בבית ספר ולדורף ומשמעותם לחינוך ולהוראה | מור גולדשמידט','עבודה סמינריונית','עבודה סמינריונית | מור גולדשמידט | אוגוסט 2011 מבוא עבודה זו מוגשת כעבודה סמינריונית במסגרת קורס של האופרה במאה ה-20 וה-21. היא עוסקת בתוכנית הלימודית בתחום המוסיקה בבית…','./lib-p2319.html',NULL,'2018',0,49,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3245','רגע היציאה מהכיתה: על אמנות הפרידה בסוף יום לימודים','מאמר','כיצד רגע הפרידה בסוף יום הלימודים משפיע על התלמידים? על חשיבות המעברים, סגירה פדגוגית ואמנות הפרידה בחינוך ולדורף.','./lib-p3245.html',NULL,'2026',0,1000,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3242','אומנות הושבת התלמידים בכיתה','מאמר','סידור מקומות הישיבה בכיתת ולדורף הוא אינו רק עניין לוגיסטי – הוא כלי חינוכי ראשון במעלה. הרצון ליצור ריתמוס נכון ואווירה לימודית תומכת דורש מאיתנו התחשבות רבה: החל…','./lib-p3242.html',NULL,'2026',0,1001,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3240','מבט על פלא החברות ארוכת השנים','מאמר','איך זה קורה שבוגרים ובוגרות שסייימו ללמוד לפני שנים, עדיין בוחרים להעביר את ימי החופש היקרים שלהם יחד מעבר לים? מהו ה"דבק" שנזרע בנפשם ומחזיק מעמד לאורך שנים? מאמר על…','./lib-p3240.html',NULL,'2026',0,1002,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3236','איך נולדת תקופה?','מאמר','מה באמת קורה מאחורי הקלעים של בניית תקופה בחינוך ולדורף? עבור הילדים, התקופה מתחילה כשהמורה נכנס לכיתה ומתחיל ללמד. אבל עבור המחנך היא מתחילה שבועות ואף חודשים קודם לכן.…','./lib-p3236.html',NULL,'2026',0,1003,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3218','זה היה בחברות – מדריך למחנך להתמודדות עם אלימות ומשחקי נערים בגיל המצווה','מאמר','כשבני כיתה ו'' נכנסים מההפסקה חבולים וסוערים, אנחנו המחנכים ניצבים בפני צומת מורכב. האם זו אלימות שיש להעניש עליה, או שפה פנימית של כוחות רצון המחפשים ערוץ לביטוי? במאמר…','./lib-p3218.html',NULL,'2026',0,1004,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3215','ימי מונדיאל: מה בין כדורגל ובין חינוך ולדורף?','מאמר','כדורגל הוא ללא ספק המשחק הפופולרי ביותר בעולם. עבור ילדים רבים, הוא אינו רק פעילות גופנית אלא מרכז הזהות החברתית שלהם, שפה בינלאומית ומושא להערצה. עם זאת, בתוך מסורת…','./lib-p3215.html',NULL,'2026',0,1005,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3201','אחריות אישית: ממושג פילוסופי לפרקטיקה חינוכית ואזרחית','מאמר','מאמר הבוחן את ערך האחריות האישית כגשר בין חירות הפרט למחויבות חברתית. גלו את המתח שבין האתיקה המוסרית לגישה התועלתנית, את הבשורה של האנתרופוסופיה וחינוך ולדורף בטיפוח…','./lib-p3201.html',NULL,'2026',0,1006,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3197','"קבל את הילד ביראה, חנך אותו באהבה ושלחהו לדרכו בחירות"','מאמר','חזון החינוך על פי רודולף שטיינר: בין יראה, אהבה וחירות בשנת 1919, במסגרת הכשרת המורים הראשונה של בית ספר ולדורף, טבע רודולף שטיינר את המשפט שהפך לאבן היסוד של הגישה…','./lib-p3197.html',NULL,'2026',0,1007,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3186','מעבר לעיקול הדרך: מדוע הריקנות של המחנך היא הצלחתו הגדולה ביותר?','מאמר','מאת: ירון זנבל , מרץ 2026 אחרי שנים של מסע משותף, מגיע רגע הפרידה הטעון. מדוע הריקנות שחש המחנך היא בעצם עדות להצלחה חינוכית? ואיך הופכת ה"שמש" הכיתתית ל"ירח" המלווה…','./lib-p3186.html','ירון זנבל','2026',0,1008,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3181','אידיאל המחנך ל-8 שנים בחינוך ולדורף פוגש את המציאות','מאמר','מאת: לינה בטשון מעווד וירון זנבל בבסיס חינוך ולדורף עומד האידיאל של מחנך המלווה את כיתתו לאורך כל שנות בית הספר היסודי (מכיתה א'' ועד ח''). מודל זה מבקש לייצר עבור הילד…','./lib-p3181.html',NULL,'2026',0,1009,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3178','תקופות הלימוד (הבלוקים) בכיתות א''-ט''','מאמר','מאת ירון זנבל, מרץ 2026 תקופות הלימוד (הבלוקים) הן מאבני היסוד של פדגוגיית ולדורף. בשיטה זו, במקום מערכת שעות מקוטעת, התלמידים צוללים לנושא אחד לעומק במשך מספר שבועות…','./lib-p3178.html','ירון זנבל','2026',0,1010,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3169','למידה מרחוק בעת חירום בחינוך ולדורף','מאמר','גם בלמידה מרחוק, חינוך ולדורף נשאר נאמן לעקרונותיו. הלמידה המקוונת בחירום אינה הופכת לדיגיטלית יותר, אלא ל"אנושית יותר" – היא משתמשת בטכנולוגיה כגשר זמני כדי לאפשר לילד…','./lib-p3169.html','ירון זנבל','2026',0,1011,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3164','מקונפליקט לחיבור: ריפוי חברתי באמצעות פרקטיקות בהשראת חינוך וולדורף','מאמר','המאמר, שנכתב בידי אייל בלוך ותום שייפר, מציג מסע מבוסס עקרונות לשיקום חברתי באזורי סכסוך. המאמר מתבסס על שלושה עשורים של עבודה בשטח ומשלב בין הפילוסופיה החינוכית של…','./lib-p3164.html',NULL,'2026',0,1012,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3147','פרדוקס הדיגיטציה בחינוך: בין קדמה טכנולוגית לבין נסיגה קוגניטיבית','מאמר','מאת: ירון זנבל בעוד מערכת החינוך דוהרת לעבר דיגיטציה מלאה תחת ההבטחה להכין את התלמידים למאה ה-21, המציאות בשטח חושפת תמונה הפוכה ומדאיגה. המסכים, שאמורים היו להנגיש ידע,…','./lib-p3147.html',NULL,'2026',0,1013,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3145','מה הטמפרמנט שלי?','מאמר','הרבה לפני שהכרנו את כל החומרים שבטבלה המחזורית, היוונים העתיקים האמינו שהעולם מורכב מ-4 יסודות בסיסיים שיוצרים את כל החומרים שבעולם – אש 🔥, מים 💧, רוח 🌬️ ואדמה ⛰️.…','./lib-p3145.html',NULL,'2026',0,1014,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3139','המהפכה של גיל הנעורים והמענה של חינוך ולדורף','מאמר','מאת ירון זנבל, ינואר 2026 חינוך ולדורף בגילאי חט"ב מבקש לבנות עבור המתבגר "כלי שיט" שייסיע לו במסע המטלטל בין "יבשת" הילדות הבטוחה, לבין "אי" ההתבגרות. דרך שילוב בין…','./lib-p3139.html','ירון זנבל','2026',0,1015,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3137','שברים פשוטים?! אתגרים בהוראת השברים והמענה של חינוך ולדורף','מאמר','מאת ירון זנבל, ינואר 2026 לימוד שברים נחשב לאחת המשימות המאתגרות ביותר במתמטיקה של בית הספר היסודי, עד כדי כך שבעבר הרחוק הם נלמדו רק ברמה האוניברסיטאית – המעבר למספרים…','./lib-p3137.html','ירון זנבל','2026',0,1016,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3134','בין המוביל לבין המאסף: טמפרמנט המחנך כמפת דרכים חינוכית','מאמר','מאת ירון זנבל, ינואר 2026 המאמר מציג את עבודת המחנך דרך המטאפורה של הטיול השנתי, הנעה בין המורה המוביל המקרין ביטחון בראש השיירה למורה המאסף המלווה ברגישות מאחור. דרך…','./lib-p3134.html','ירון זנבל','2026',0,1017,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3130','הערכה מילולית בטווחים: מודדים את בריאות הלמידה','מאמר','מאת: ירון זנבל, דצמבר 2025 אבחון במקום ציון הערכה מבוססת ציון מספרי יוצרת אוטומטית השוואה ודירוג. הבעיה אינה רק הציון עצמו, אלא המסר המוסרי והחברתי שהוא משדר. חינוך…','./lib-p3130.html','ירון זנבל','2025',0,1018,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3112','המסע המחנך: טיולים בחינוך ולדורף','מאמר','לצאת מהכיתה, לפגוש את העולם, להקשיב לדממה ולנשום את הטבע. הטיול בחינוך ולדורף אינו רק מטרה, אלא אמצעי לעיצוב אדם מחובר, המסוגל לאהוב את העולם הרחב. חווית הטיול, המסומנת…','./lib-p3112.html',NULL,'2025',0,1019,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3110','התבוננות בילד: פרקטיקה של הכרה וריפוי','מאמר','מאת: ירון זנבל, נובמבר 2025 מהי ההתבוננות? ההתבוננות בילד היא פרקטיקה פנומנולוגית-רפלקטיבית ושיטה טיפולית המעוגנת בתורתו הביוגרפית-התפתחותית של רודולף שטיינר. בחדר…','./lib-p3110.html','ירון זנבל','2025',0,1020,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3106','בינה מלאכותית בשירות חינוך ולדורף: נתיב לשימוש מושכל','מאמר','האם בינה מלאכותית (AI) מאיימת על עקרונות חינוך ולדורף, או שמא היא כלי הכרחי שיש לרתום? המאמר מתווה נתיב סינרגטי המבחין בין שימוש המורים ב-AI לבין הוראת התלמידים ומציע כי…','./lib-p3106.html',NULL,'2025',0,1021,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3104','השילוב בין אינטואיציות המחנך ובין יכולות AI בליהוק הצגות כיתה','מאמר','הצגת הכיתה בחינוך ולדורף מוגדרת כשיא הפעילות החינוכית של בית הספר והיא מהווה כור היתוך יצירתי, רגשי וחברתי. בהיותה תהליך מורכב, היא מטילה עומס על המחנכים וצוות ביה"ס.…','./lib-p3104.html','ירון זנבל','2025',0,1022,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3099','איך לקבל החלטת גורל','מאמר','כאשר אנו מזהים קושי או צורך בשינוי, והפתרון כרוך בבחירה בין חלופות – אנו עומדים בפני ה צורך לקבל החלטה . אנו נדרשים לקבל החלטות פעמים רבות במהלך חיינו – לצד החלטות…','./lib-p3099.html','ירון זנבל','2025',0,1023,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3086','מדריך לכריכת מחברות תקופה לספר השנה','מאמר','מחברת התקופה בחינוך ולדורף היא אמצעי מרכזי לתיעוד תהליך הלמידה שמתרחש במהלך תקופות הלימוד. כל מחברת כוללת סיכומים בכתב, ציורים, סיפורים, שירים וכתיבה אישית של התלמיד.…','./lib-p3086.html','ירון זנבל','2025',0,1024,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3088','התפתחות פיזית ונפשית בשלושת השביעונים הראשונים','מאמר','האדם נתפס כמורכב מארבעה גופים: הגוף הפיזי, הגוף האתרי, הגוף האסטרלי והגוף הרוחי. כל אחד מהם קשור לתחומים שונים של ההוויה האנושית ופועל ברמות שונות של קיום. בחינוך ולדורף…','./lib-p3088.html','ירון זנבל','2025',0,1025,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p3020','הפוך גוטה. הפוך','מאמר','המאמר משווה בין שתי מערכות גדולות – בנקאית וחינוכית – ומנתח את ניסיונותיהן ליישם טכנולוגיה מתקדמת. במערכת הבנקאית, ניסיון להחליף סניפים מסורתיים במערכת מתוקשבת עתידנית…','./lib-p3020.html','ירון זנבל','2025',0,1026,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2851','המעגל בחינוך ולדורף','מאמר','המעגל בחינוך ולדורף – עיבוד של המאמר " Why do we have Circle Time throughout the Grades? " שכתבה Kolea Quincey מתוך WaldorfToday בחינוך ולדורף נהוגה ושגורה העבודה עם…','./lib-p2851.html','ירון זנבל','2022',0,1027,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2810','תקופות בוטניקה בכיתות ה''-ו'': לצמוח עם הילדים','מאמר','מפשוט למורכב, מרך למעוצב, מדמיוני למציאותי, מתלות לעצמאות. התבגרות. יא וַיֹּאמֶר אֱלֹהִים, תַּדְשֵׁא הָאָרֶץ דֶּשֶׁא עֵשֶׂב מַזְרִיעַ זֶרַע, עֵץ פְּרִי עֹשֶׂה פְּרִי…','./lib-p2810.html','ירון זנבל','2022',0,1028,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2803','לספר סיפורים (בע"פ) בחינוך ולדורף','מאמר','חינוך ולדורף מושתת על סיפור סיפורים. מהסיפור במעגל בגן הילדים ועד שיעורי המדעים בתיכון. ולא סתם סיפור – הכוונה היא לסיפור בעל פה, ללא ספר. מדוע הסיפור בחינוך ולדורף כה…','./lib-p2803.html','ירון זנבל','2022',0,1029,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2665','תפקיד מנהל בית הספר, ניהול משותף, מנהיגות ואחריות בבית ספר ולדורף','מאמר','אפריל 2020 הקדמה המאמר נשען על חומרים שונים מעולם המנהיגות האופקית. העריכה שלו נעשית בפסח, בתקופת הקורונה. בתקופה זו המתח שבין כוחות עבר ועתיד מתחדד. הדרישה להתחדשות…','./lib-p2665.html','רונן האן','2020',0,1030,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2650','למידה מרחוק מתוך השקפת חינוך וולדורף','מאמר','מאת: Martyn Rawson תרגום: גיא פרי הקדמה בהינתן העוצר הנוכחי והצורך הכפוי בלמידה מרחוק, מהבית, כדאי להקדיש זמן לחשיבה מחודשת של עקרונות הלמידה על פי השקפת חינוך וולדורף.…','./lib-p2650.html','מרטין רואוסון','2020',0,1031,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2591','הכיתה כמרחב להתחנכות','מאמר','או הדרך הפנימית של מורה הכיתה מאת: אורי עברי פורסם ב אדם עולם באביב 2013 שתי סיבות מביאות אותי לכתוב מאמר זה על דרכו הפנימית של המורה. ראשית, כמורה וותיק יחסית מצאתי…','./lib-p2591.html','אורי עברי','2020',0,1032,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2585','על שאלות חינוכיות בגיל ההתבגרות המינית (כיתות ו'', ז'', ח''): ליווי חינוכי וחינוך מיני','מאמר','מבוא זה זמן רב שהשאלה כיצד נכון ללוות את שלב ההתעוררות של נערות ונערים לזהותם האישית בגיל טרום הנעורים (כיתות ז-ח) חייה בתוכי. האם ההנחיות ששטיינר נתן בהתייחסו ללווי…','./lib-p2585.html','אורי עברי','2020',0,1033,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2398','הקולגיום','מאמר','מאמר זה מציע תפיסה כללית לבניית ישיבות צוות. במונח צוות אפשר להכליל מחלקה, ענף גם כל העובדים של ארגון לא גדול , למשל עד 60-70 משתתפים. הדוגמא וההשראה מתבססות על ישיבת…','./lib-p2398.html','רונן האן','2018',0,1034,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2391','זו לא התורה כולה – חינוך ולדורף ויהדות','מאמר','שטיינר דיבר על רליגיוזיות כרגש עמוק של הכרת תודה, ממשיכיו בחינוך ולדורף מתייחסים ללאומיות כבסיס לתחושת שייכות. כיצד משלבים יהדות וציונות בלימודי ולדורף בישראל? הרב…','./lib-p2391.html','אילה שני','2018',0,1035,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2325','עיצוב מרחב פיזי ברוח החינוך','מאמר','תכנון מבנה גן ילדים ולדורף בהרדוף האם וכיצד ניתן לתכנן מבנה כך שיוכל לתמוך בפעילויות חינוכיות, באווירה חינוכית ובערכים חינוכיים מסוימים? כיצד אפשר לחבר בין תכנון אדריכלי…','./lib-p2325.html','דרור צור וגלעד גולדשמידט','2018',0,1036,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2328','חינוך ולדורף ואתגרי הזמן','מאמר','מאת: אורי עברי [המאמר ב קובץ word ] הציטוטים מובאים מתוך סדרת ההרצאות של שטיינר שנקראות בעברית "חינוך וחיים רוחיים מודרנים" ואשר ניתנו כבסיס לייסוד חינוך ולדורף באנגליה.…','./lib-p2328.html','אורי עברי','2018',0,1037,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2327','דרכו הפנימית של המורה או "חנוך לנער לפי דרכו"','מאמר','מאת: אורי עברי [המאמר כ קובץ word ] שתי סיבות מביאות אותי לכתוב מאמר זה על דרכו הפנימית של המורה. ראשית כמורה בשבתון מצאתי עצמי מלווה מורים עמיתים בדרכם ומתוך עבודתי עלו…','./lib-p2327.html','אורי עברי','2018',0,1038,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2323','22 שאלות ותשובות על חינוך ולדורף','מאמר','מה מיוחד בבית ספר ולדורף? הרושם הראשון שמקבלים מהנעשה בבית ספר יסודי ברוח חינוך ולדורף הוא של פעילות אמנותית מתמשכת: הילדים שרים, מנגנים, רוקדים, מציירים, רושמים,…','./lib-p2323.html','גלעד גולדשמידט','2018',0,1039,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2038','א. מבוא','ספר','הספר "חינוך ולדורף – עקרונות ויישומים" נכתב על-ידי מורי בית הספר ולדורף הרדוף, סתיו 2000 הדברים שיובאו לעיל מנסים להציג את חינוך ולדורף כפי שהוא התפתח ומיושם בבתי הספר…','./lib-p2038.html','מורי בית הספר ולדורף הרדוף','2000',0,2000,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2042','ב. יסודות חינוך ולדורף','ספר','חינוך ולדורף נוסד בתחילת המאה על-ידי המחנך, הפילוסוף והוגה הדעות רודולף שטיינר (1861-1925). בית-הספר הראשון הוקם כבית-ספר לילדי פועלים במפעל "ולדורף-אסטוריה" בעיר…','./lib-p2042.html','מורי בית הספר ולדורף הרדוף','2000',0,2001,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2045','ג. בתי-ספר ולדורף בארץ','ספר','בארץ פועלים כיום שלשה בתי- ספר ולדורף: בירושלים – בי"ס "אדם", עם תשע כיתות, א'' עד ט''; בטבעון – בי"ס "שקד", עם שמונה כיתות א'' עד ח''; ובי"ס ולדורף הרדוף, בקיבוץ הרדוף…','./lib-p2045.html','מורי בית הספר ולדורף הרדוף','2000',0,2002,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2047','ד. ניהול בית-הספר ועבודת המורים','ספר','כאשר התבקש רודולף שטיינר (מייסד חינוך ולדורף) לעזור בהקמת בית-הספר ולדורף הראשון (1919), הוא אסף סביבו קבוצת מורים וניסה להכשירם להוראה בתקופה הקצרה שעמדה לרשותם עד…','./lib-p2047.html','מורי בית הספר ולדורף הרדוף','2000',0,2003,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2051','ה. עבודה עם הורים – מעורבות הורים','ספר','השותפים הישירים להוויית החיים הבית-ספרית הנם הילדים, המורים וההורים. כאשר מנסים ליצור איכויות שהנן מעבר להקניית ידע ואינפורמציה, עולה שאלת החיים המשותפים בקהילת…','./lib-p2051.html','מורי בית הספר ולדורף הרדוף','2000',0,2004,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2054','ו. על כמה צדדים מעשיים','ספר','בפרקים הבאים יעשה הניסיון להביא בקיצור כמה מן הצדדים המעשיים של העבודה הפדגוגית בבית-הספר. בכל תאור צריך רק לקחת בחשבון, שאת הדברים החשובים ובעלי המשמעות אין אפשרות לתאר…','./lib-p2054.html','מורי בית הספר ולדורף הרדוף','2000',0,2005,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2059','ז. מחיי הכיתה – כמה דוגמאות למתודות ההוראה','ספר','בפרק זה יובאו כמה דוגמאות מעבודה של כיתות שונות בבתי-הספר ולדורף בארץ. בהביאנו דוגמאות מהעבודה המעשית של חיי בית-הספר יש לזכור שבבית-ספר ולדורף אין דרך אחת ויחידה ללמד…','./lib-p2059.html','מורי בית הספר ולדורף הרדוף','2000',0,2006,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2061','ח. סמכות וחופש – שאלת הדמוקרטיה בחינוך ולדורף','ספר','הדמוקרטיה הפכה בעת החדשה, ובמיוחד במאה ה- 20 לאחד מהערכים המרכזיים של התרבות המערבית. אולם הדמוקרטיה אינה תופעה מובנת מאליה בתולדות האנושות. את רובה הגדול של עברה עשתה…','./lib-p2061.html','מורי בית הספר ולדורף הרדוף','2000',0,2007,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2062','ט. הערכה בחינוך ולדורף','ספר','תהליכי הערכה נכונים אינם מנותקים מהתהליך החינוכי אותו הם אמורים להעריך. תהליכי הערכה מנותקים וכביכול אוביקטיביים אינם חלק מהתהליך הלימודי אליו שואף בית-ספר ולדורף. כמו…','./lib-p2062.html','מורי בית הספר ולדורף הרדוף','2000',0,2008,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2063','י. הכשרת המורים ברוח חינוך ולדורף – סמינר המורים','ספר','המורים המלמדים בבית-הספר עברו כולם (או שעדיין עוברים במקביל לעבודתם) הכשרת מורים ברוח חינוך ולדורף. הכשרה זו נמשכת כשלוש שנים ומהווה תנאי לקבלת המורה לעבודה בבית-הספר.…','./lib-p2063.html','מורי בית הספר ולדורף הרדוף','2000',0,2009,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2064','יא. כמה צדדים טכניים','ספר','א. מעמד חוקי והכרה בתי-ספר ולדורף בארץ הוכרו כבתי-ספר ממלכתיים, רשמים במסגרת משרד החינוך. בתי-הספר מקבלים את התקציבים המגיעים לכל בית-ספר ונתונים לאותו פיקוח. עקב אופיים…','./lib-p2064.html','מורי בית הספר ולדורף הרדוף','2000',0,2010,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2065','יב. אנשים שונים אודות חינוך ולדורף','ספר','"אם היה לי ילד בגיל בית-ספר, הייתי שולחו לאחד מבתי-הספר ולדורף" סול בלו – סופר וחתן פרס נובל לספרות "רוב הילדים שמתחנכים במסגרת חינוך ולדורף הנם שמחים, נבונים, מקבלים,…','./lib-p2065.html','מורי בית הספר ולדורף הרדוף','2000',0,2011,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2066','יג. מדברי תלמידים בתיכון ולדורף הרדוף על בית ספרם','ספר','" … כאן זה לא רק כיף לי, ולא רק שהכל כה שונה, אלא כאן לומדים קשה ועובדים, אך יחד עם זה מאד נהנים. כאן אנחנו חיים בתוך הדרך שבה אנו רוצים לחיות." תלמידה בכיתה י'' "בבית…','./lib-p2066.html','מורי בית הספר ולדורף הרדוף','2000',0,2012,strftime('%s','now'),strftime('%s','now'));
INSERT OR REPLACE INTO library (id,title,kind,description,url,author,date,demo,position,created_at,updated_at) VALUES ('lb-p2067','יד. שירים ודקלומים מעבודות התלמידים','ספר','שיר המשאלה יש לי משאלה היא קטנה וגם גדולה שיהיה שלום בין ארצות ושיהיה שלום בין אחים ואחיות שנדע לאהוב כל אדם ואדם למרות שאף אחד לא מושלם. יש לי משאלה היא קטנה וגם גדולה…','./lib-p2067.html','מורי בית הספר ולדורף הרדוף','2000',0,2013,strftime('%s','now'),strftime('%s','now'));
